- pom.xml
- src/main/java/org/wickedsource/docxstamper/DocxStamper.java
- src/main/java/org/wickedsource/docxstamper/processor/repeat/ParagraphRepeatProcessor.java
- src/main/java/org/wickedsource/docxstamper/processor/repeat/RepeatDocPartProcessor.java
- src/main/java/org/wickedsource/docxstamper/util/CommentUtil.java
- src/main/java/org/wickedsource/docxstamper/util/CommentWrapper.java
Full changelist to allow repeatDocPart to work recursively, extracting whole doc part into an in memory template, stamped using the same context and resolvers configuration, before inserting the whole thing back in place inside the original memo.
Original doc part and comments are removed on commit.
Limitation : comments inside doc part must not overlap the original comment range start/end for it to work.
> Recursive repeat doc part

- src/main/java/org/wickedsource/docxstamper/processor/repeat/RepeatDocPartProcessor.java
The insertion was made at the top of the document after processing repeatDocPart comments.
The right parent is used now for determining the position for inserting generated doc parts and figuring the right position to insert them at.
> fixed introduced regression in 1.4.7-SNAPSHOT

- src/main/java/org/wickedsource/docxstamper/el/ExpressionResolver.java
- src/main/java/org/wickedsource/docxstamper/el/Matcher.java
- src/main/java/org/wickedsource/docxstamper/util/CommentUtil.java
- src/main/java/pro/verron/docxstamper/utils/ProcessorExceptionHandler.java
- src/main/java/pro/verron/docxstamper/utils/ThrowingRunnable.java
Refactor wires simplified and cleaned up for better readability in various classes such as CommentUtil, Matcher, and ExpressionResolver. Additional JavaDoc documentation has been added to further enhance understanding. Changes in ProcessorExceptionHandler improve thread safety with CopyOnWriteArrayList and offer extended documentation. Minor changes have been applied in ThrowingRunnable class too.
> Refactor and document various classes in docxstamper package

- .mailmap
Multiple email addresses have been associated with their corresponding users in the .mailmap file. This change will help in attributing commits accurately and managing contributors' identifiers more efficiently.
> Add multiple entries to .mailmap

- README.adoc
The display of status badges for the build processes in the README file has been adjusted. The previous direct URLs were replaced by dynamic github references. This allows for a consistent display regardless of the repository's location.
> Update status badges in README

- src/main/java/pro/verron/docxstamper/preset/resolver/Resolvers.java
Modified the return types of various methods in the Resolvers class. They previously returned specific resolvers (LocalTimeResolver, LocalDateTimeResolver, etc.), but now they all return ObjectResolver. This change provides more flexibility in handling different types of objects.
> Change return type to ObjectResolver in Resolvers methods

- pom.xml
This commit updates the docx4j dependency version in pom.xml from 11.4.9 to 11.4.11. The change helps to incorporate improvements and fixes from the latest versions, ensuring that our project stays current and stable.
> Update docx4j dependency version

- examples/pom.xml
The commit changes the dependency in the pom.xml file. It has replaced 'pro.verron:docx-stamper:1.6.8' with 'pro.verron.office-stamper:engine:2.0-SNAPSHOT'. This ensures the use of updated and relevant applications in the software system.
> Update dependency in pom.xml

- engine/src/test/java/pro/verron/officestamper/test/BasicExcelTest.java
- engine/src/test/java/pro/verron/officestamper/test/BasicPowerpointTest.java
- engine/src/test/java/pro/verron/officestamper/test/BasicWordTest.java
- engine/src/test/java/pro/verron/officestamper/test/DefaultTests.java
- engine/src/test/java/pro/verron/officestamper/test/FailOnUnresolvedPlaceholderTest.java
- engine/src/test/java/pro/verron/officestamper/test/MultiSectionTest.java
- engine/src/test/java/pro/verron/officestamper/test/MultiStampTest.java
- engine/src/test/java/pro/verron/officestamper/test/NullPointerResolutionTest.java
- engine/src/test/java/pro/verron/officestamper/test/PlaceholderReplacementInHeaderAndFooterTest.java
- engine/src/test/java/pro/verron/officestamper/test/PlaceholderReplacementInTextBoxesTest.java
- engine/src/test/java/pro/verron/officestamper/test/RepeatDocPartBadPlaceholderTest.java
- engine/src/test/java/pro/verron/officestamper/test/SpelInjectionTest.java
- engine/src/test/java/pro/verron/officestamper/test/StampTableTest.java
- engine/src/test/java/pro/verron/officestamper/test/TestUtils.java
Modified the resource retrieval process in various test classes from using Files.newInputStream or getResource method from DefaultTests to using the getResource method from TestUtils. This revision not only simplifies the code but also makes the resource retrieval process more modular and easy to manage.
> [test] Refactor TestUtils for resource retrieval

- pom.xml
The pom.xml has been updated to include 'engine' and 'examples' as submodules. This change helps in the full project's components in one command.
> Add 'engine' and 'examples' modules to pom.xml

- engine/src/main/java/module-info.java
- engine/src/main/java/org/wickedsource/docxstamper/DocxStamperConfiguration.java
- engine/src/main/java/org/wickedsource/docxstamper/processor/BaseCommentProcessor.java
- engine/src/main/java/pro/verron/officestamper/core/DocxStamper.java
- engine/src/main/java/pro/verron/officestamper/preset/CommentProcessorFactory.java
- engine/src/main/java/pro/verron/officestamper/preset/OfficeStampers.java
- examples/src/main/java/pro/verron/officestamper/Examples.java
- examples/src/main/java/pro/verron/officestamper/Main.java
The DocxStamper class has been moved from org.wickedsource.docxstamper to pro.verron.officestamper.core as per the recent refactoring plan. The import statements across all files using this class have also been adjusted accordingly. The legacy code in examples regarding the use of DocxStamper inspired diagnostic methods has been removed.
> BREAKING CHANGE: Refactor DocxStamper class to new package

- engine/src/main/java/module-info.java
- engine/src/main/java/pro/verron/officestamper/core/DocxStamperConfiguration.java
- engine/src/main/java/pro/verron/officestamper/preset/OfficeStamperConfigurations.java
The file DocxStamperConfiguration has been moved from org.wickedsource.docxstamper to pro.verron.officestamper.core package. Additionally, the module-info.java file has been updated to reflect these changes. Deprecated annotation is also removed from this class.
> BREAKING CHANGE: Refactor and relocate DocxStamperConfiguration

- engine/src/main/java/org/wickedsource/docxstamper/processor/repeat/ParagraphRepeatProcessor.java
- engine/src/main/java/org/wickedsource/docxstamper/processor/repeat/RepeatDocPartProcessor.java
- engine/src/main/java/org/wickedsource/docxstamper/processor/repeat/RepeatProcessor.java
Adjusted code formatting for consistency and readability across multiple classes. Removed deprecated methods in RepeatProcessor, RepeatDocPartProcessor, and ParagraphRepeatProcessor classes, as they are no longer being used in the core library. This simplifies the codebase and reduces potential points of failure.
> refactor!: remove deprecated methods

- engine/src/main/java/org/wickedsource/docxstamper/util/DocumentUtil.java
Deleted the methods getParagraphsFromObject, getTableFromObject, getTableRowsFromObject and getTableCellsFromObject that were previously marked as deprecated in the DocumentUtil class. These methods were not being used internally and were scheduled for removal.
> refactor!: Remove deprecated methods in DocumentUtil class

- engine/src/main/java/org/wickedsource/docxstamper/processor/CommentProcessorRegistry.java
- engine/src/main/java/pro/verron/officestamper/api/AbstractCommentProcessor.java
- engine/src/main/java/pro/verron/officestamper/api/CommentProcessor.java
- engine/src/test/java/pro/verron/officestamper/test/CustomCommentProcessor.java
The setDocument method in CommentProcessor and related classes has been removed as it is no longer necessary. The document is now passed through the commitChange method or the constructor. This change simplifies the code and removes the need for deprecated methods.
> refactor!: Remove deprecated setDocument method from CommentProcessor

- engine/src/main/java/pro/verron/officestamper/api/OfficeStamperConfiguration.java
- engine/src/main/java/pro/verron/officestamper/core/DocxStamperConfiguration.java
The deprecated methods related to null value replacement were removed from the OfficeStamperConfiguration and DocxStamperConfiguration classes. These methods have been deprecated since version 1.6.7, and their use was discouraged due to a change in the application's handling of null values.
> refactor!: Remove deprecated null value replacement methods

- engine/src/main/java/pro/verron/officestamper/core/CommentUtil.java
- engine/src/main/java/pro/verron/officestamper/core/DocxStamper.java
- engine/src/main/java/pro/verron/officestamper/core/DocxStamperConfiguration.java
- engine/src/main/java/pro/verron/officestamper/preset/Resolvers.java
This commit removes several methods previously marked as deprecated across various classes. It also changed the visibility of Null2DefaultResolver from public to private in the Resolvers class. This ensures a cleaner code base and encourages usage of up-to-date methods and configurations.
> Remove deprecated methods and updates

- engine/src/main/java/org/wickedsource/docxstamper/processor/repeat/RepeatProcessor.java
The method stampEmptyContext() within the RepeatProcessor class was removed as it is no longer needed in the code. This method was creating a new RepeatProcessor; however, it was not used in the overall functions of this class.
> refactor!: Remove unused stampEmptyContext method from RepeatProcessor

- engine/src/main/java/pro/verron/officestamper/core/DocxStamper.java
- engine/src/main/java/pro/verron/officestamper/core/DocxStamperConfiguration.java
The deprecated annotations and comments have been removed from the DocxStamperConfiguration and DocxStamper classes. This change simplifies the code and removes outdated information that could potentially confuse users.
> refactor: Remove deprecated annotations from DocxStamper classes

- engine/src/main/java/pro/verron/officestamper/core/DocxStamper.java
- engine/src/main/java/pro/verron/officestamper/preset/CommentProcessorFactory.java
- engine/src/main/java/pro/verron/officestamper/preset/OfficeStampers.java
The DocxStamper class is refactored to remove the generic type. This change has been reflected in the related classes and methods that use this class, such as CommentProcessorFactory and OfficeStampers, by creating new instances of DocxStamper without type specification.
> refactor!: Remove generic typing from DocxStamper class

- engine/src/main/java/pro/verron/officestamper/core/Matcher.java
- engine/src/main/java/pro/verron/officestamper/core/PlaceholderFinder.java
- engine/src/main/java/pro/verron/officestamper/core/Placeholders.java
- engine/src/main/java/pro/verron/officestamper/core/StandardPlaceholder.java
- engine/src/main/java/pro/verron/officestamper/core/expression/package-info.java
The PlaceholderFinder and Matcher classes which were previously located in the 'core.expression' package have been moved to the 'core' package. The 'core.expression' package has subsequently been deleted. This refactoring effort was undertaken to improve the organization of the code.
> refactor!: Moved classes from 'core.expression' to 'core' package

- engine/src/main/java/module-info.java
The recent changes in 'module-info.java' involves the removal of exports and opens lines related to `pro.verron.officestamper.core`. This is part of cleanup operation of removing the experimental code references that are no longer needed.
> refactor!: Remove experimental code exports in module-info

- engine/src/main/java/module-info.java
- engine/src/main/java/pro/verron/officestamper/core/CommentProcessorRegistry.java
- engine/src/main/java/pro/verron/officestamper/core/DocxStamper.java
- engine/src/main/java/pro/verron/officestamper/core/ExpressionResolver.java
- engine/src/main/java/pro/verron/officestamper/core/PlaceholderReplacer.java
- engine/src/main/java/pro/verron/officestamper/core/StandardMethodExecutor.java
- engine/src/main/java/pro/verron/officestamper/core/StandardMethodResolver.java
In this commit, several org.wickedsource.docxstamper.el classes were moved into the pro.verron.officestamper.core package. These include StandardMethodResolver, StandardMethodExecutor, and ExpressionResolver. This restructuring also involved updating import statements in PlaceholderReplacer, CommentProcessorRegistry, and DocxStamper classes. The org.wickedsource.docxstamper.el package was subsequently removed from module-info.java.
> refactor!: docxstamper classes into officestamper.core package

- engine/src/main/java/pro/verron/officestamper/core/ExpressionResolver.java
Added @Nullable annotation to the resolve method in the ExpressionResolver class. This change provides explicit information about the potential return of null values from this method, improving code readability and predictability.
> doc: Add @Nullable annotation to resolve method in ExpressionResolver

- engine/src/main/java/pro/verron/officestamper/api/AbstractCommentProcessor.java
- engine/src/main/java/pro/verron/officestamper/api/CommentProcessor.java
- engine/src/main/java/pro/verron/officestamper/core/CommentProcessorRegistry.java
Re-organized code blocks in CommentProcessorRegistry for better readability and understanding. Also, improved method parameter types with applicable annotations.
> doc: CommentProcessorRegistry code for readability

- engine/src/main/java/org/wickedsource/docxstamper/util/DocumentUtil.java
- engine/src/main/java/org/wickedsource/docxstamper/util/IndexedRun.java
- engine/src/main/java/org/wickedsource/docxstamper/util/ParagraphUtil.java
- engine/src/main/java/pro/verron/officestamper/api/StringResolver.java
- engine/src/main/java/pro/verron/officestamper/core/CommentProcessorRegistry.java
- engine/src/main/java/pro/verron/officestamper/core/PlaceholderReplacer.java
- engine/src/main/java/pro/verron/officestamper/core/RunUtil.java
- engine/src/main/java/pro/verron/officestamper/core/StandardParagraph.java
- engine/src/main/java/pro/verron/officestamper/preset/CommentProcessorFactory.java
- engine/src/main/java/pro/verron/officestamper/preset/Resolvers.java
The RunUtil class has been moved from the 'org.wickedsource.docxstamper.util' package to the 'pro.verron.officestamper.core' package. Relevant import adjustments in other classes have been applied to reflect this change.
> feat: move RunUtil to core package

- engine/src/main/java/pro/verron/officestamper/core/ObjectResolverRegistry.java
- engine/src/main/java/pro/verron/officestamper/core/RunUtil.java
Included the @Nullable annotation for the 'object' parameter in ObjectResolverRegistry and 'maxWidth' parameter in RunUtil. This allows the mentioned variables to accept null values, providing more flexibility in usage.
> feat: allow nullable object and maxWidth parameters in core

- .github/workflows/pages.yml
- .github/workflows/release.yml
- engine/pom.xml
- examples/pom.xml
- pom.xml
Changes made to pom.xml files to adapt the project structure to a multimodal Maven project. The 'engine' and 'examples' modules now have 'office-stamper' as a parent. Also, updated GitHub action workflows to adapt to the changes.
> chore: Refactor Maven structure to multi-module project

- engine/pom.xml
- examples/pom.xml
- pom.xml
Updated the version of 'office-stamper', 'engine', and 'examples' artifacts from 2.0-SNAPSHOT to the stable version 2.0. This step is part of our process preparing for a new release.
> chore: Update versions from 2.0-SNAPSHOT to 2.0 in pom.xml files

- engine/src/main/java/pro/verron/officestamper/core/DocxStamper.java
- engine/src/main/java/pro/verron/officestamper/core/ExpressionResolver.java
Changed the constructor of ExpressionResolver to take an instance of ExpressionParser instead of SpelParserConfiguration. The ExpressionParser object is now created in DocxStamper and passed to the ExpressionResolver construction. Removed unused SpelParserConfiguration import in ExpressionResolver. This change makes ExpressionResolver class more flexible to use either SpelExpressionParser or any other implementation of ExpressionParser.
> refactor: change ExpressionResolver constructor to take ExpressionParser

- engine/src/main/java/pro/verron/officestamper/preset/CommentProcessorFactory.java
Improve the code readability and formatting in CommentProcessorFactory.java. Changes include ensuring consistent indentation, simplifying complex if conditions, removing redundant code and reducing verbosity. Made method parameters nullable where logical to do so.
> feat: Refactor and clean up CommentProcessorFactory.java

- README.adoc
This commit updates the documentation in README.adoc to reflect recent updates in library usage, the addition of new features like custom comment processors, and the shift in docx-stamper's core dependencies. Fixed broken links and updated code examples to match changes in library interface.
> feat: Update README with new syntax and library changes

- engine/pom.xml
- examples/pom.xml
- pom.xml
This commit bumps the version of office-stamper, engine, and examples from 2.0 to 2.0.1. Also, it removes the parent tag in engine and examples pom.xml files, and instead they have been given their specific groupId, artifactId, and version.
> feat: Update office-stamper, engine, examples version to 2.0.1

- README.adoc
This commit introduces v2.1.0 release note details in README which includes updated Readme how-to, Word document navigation update, exception management, version bump for spring-expression dependency and more.
A fix for v2.0.1 dependency issue was also noted.
> feat: Add v2.1.0 release notes to README

- .mvn/extensions.xml
A new file, .mvn/extensions.xml, has been created. This file incorporates a previously non-existent maven extension called 'maven-build-cache-extension' from groupId 'org.apache.maven.extensions'. Version used is 1.2.0.
> feat: add new maven extension for caching build

- engine/src/test/java/pro/verron/officestamper/test/DefaultTests.java
- engine/src/test/java/pro/verron/officestamper/test/WhitespaceTest.java
Improve test readability and organization by isolating whitespace-related tests into `WhitespaceTest.java`.
> refactor: move whitespace tests to separate class

- pom.xml
The stringifier module is no longer required and removing it streamlines the build configuration.
> fix(pom.xml): remove unused stringifier module

- README.adoc
- RELEASE_NOTES.adoc
- engine/src/main/java/pro/verron/officestamper/preset/IStamperDateFormatter.java
- engine/src/main/java/pro/verron/officestamper/preset/OfficeStamperConfigurations.java
- engine/src/main/java/pro/verron/officestamper/preset/StamperDateFormatter.java
- engine/src/test/java/pro/verron/officestamper/test/Contexts.java
- engine/src/test/java/pro/verron/officestamper/test/DateFormatTests.java
Introduce IStamperDateFormatter interface and StamperDateFormatter implementation to format java.time objects. Update README and release notes to document new feature.
This enhancement addresses issue #411, allowing Office-stamper to format date and time objects directly from standard configuration.
> feat: add date-time formatting functionality

- engine/src/test/java/pro/verron/officestamper/test/RegressionTests.java
Renamed class TestBug52 to RegressionTests for clarity. Added a new test method for issue 64 focusing on failures when calling a function defined within its own interface. Updated existing test method for issue 52 to accommodate the renaming and new organizational structure.
> Rename TestBug52 and add tests for issues 52 and 64
